<?php namespace Yaddabristol\Crud\Classes;

use Yaddabristol\Crud\Exceptions\InvalidCrudInitialisationException;

use Yaddabristol\Crud\Controllers\CrudController;

class CrudManager {

    /**
     * The directory that views are stored in. E.g. 'admin.model'
     * @var string
     */
    public $views_dir;

    /**
     * The name of the model handled by this controller.
     * @var string
     */
    public $name_singular;

    /**
     * The plural name of the model handled by this controller.
     * @var string
     */
    public $name_plural;

    /**
     * The base route for this controller.
     * @var string
     */
    public $route;

    /**
     * Classes to be added to the body tag
     */
    public $body_classes = [];

    /**
     * Index page table column headings and associated attributes
     */
    public $table_columns = [];

    /**
     * Set to true to enable file uploading.
     */
    public $has_files = false;

    /**
     * Fields to use in autogenerated form. The options specified here only
     * affect the HTML that is generated by autoform.blade.php. They do not
     * otherwise affect the application. Because of this you can easily create
     * your own field types by just creating a blade file.
     * e.g. views/fields/YOURFIELDNAME.blade.php
     */
    public $form_fields = [];

    protected $allowed_attirbutes = ['views_dir', 'name_singular', 'name_plural', 
        'route', 'body_classes', 'table_columns', 'paginate', 'form_fields'];

    /**
     * Applies a set of data to this object
     * 
     * @param  Mixed        $attributes   Array or instance of CrudController
     * @return CrudManager                Modified $this
     */
    public function initialize($attributes)
    {
        // if $attributes is an instance of crud controller pull properties,
        // otherwise ensure attributes is an array
        if(is_object($attributes) && $attributes instanceof CrudController)
            $attributes = $attributes->getCrudAttributes(); 
        elseif(!is_array($attributes))
            throw new InvalidCrudInitialisationException("Data passed in incorrect format");
    
        foreach($attributes as $attribute_name => $attribute_value) {
            if(!in_array($attribute_name, $this->allowed_attirbutes))
                throw new InvalidCrudInitialisationException("Attempted to set unrecognised value: {$attribute_name}");

            $this->$attribute_name = $attribute_value;
        }
    
        return $this;
    }

    /**
     * Adds an array of classes to the body classes array, removing duplicates
     * @param   array       $classes        classes to add
     */
    public function addBodyClasses($classes)
    {
        foreach($classes as $class) {
            $this->addBodyClass($class);
        }
    }

    /**
     * Adds a single class to the body classes array, if it isn't already present
     * @param   string      $class          class to add
     * @return  CrudManager                 $this
     */
    public function addBodyClass($class)
    {
        if(!stringTest($class))
            throw new InvalidCrudInitialisationException("Classes passed to addBodyClass(es) must be strings");

        if(!in_array($class, $this->body_classes))
            $this->body_classes[] = (string) $class;
    }

    /**
     * Adds an array of fields to the body fields array, removing duplicates
     * @param   array       $fields        fields to add
     */
    public function addFormFields($fields)
    {
        foreach($fields as $field_name => $field_data) {
            $this->addFormField($field_name, $field_data);
        }
    }

    /**
     * Adds a single field to the body fields array, if it isn't already present
     * @param   string      $field_name     field name
     * @param   string      $field_data     field data to add to array
     * @return  CrudManager                 $this
     */
    public function addFormField($field_name, $field_data, $overwrite = false)
    {
        if(!is_array($field_data))
            throw new InvalidCrudInitialisationException("Fields passed to addFormField(s) must be arrays of field data");

        if(!array_key_exists($field_name, $this->form_fields) || $overwrite)
            $this->form_fields[$field_name] = $field_data;
    }
}